### ISSUE TITLE
 a small bugs in  manual installation of zstack

### ISSUE THREAD

**Issue by yanhongchang** [zstackorg/zstackorg.github.io#1]
bugs url:http://zstack.org/installation/manual.html

it should be                 Example: sudo zstack-ctl install_db --host=192.168.0.224

![image001](https://cloud.githubusercontent.com/assets/10663031/7677998/507cab48-fd83-11e4-8666-bb3070119473.png)

**Comment by zxwing** [comment]
fixed in c172b992813532df28aa3eec31f4368c8dab317a
