### ISSUE TITLE
Root volume 进行snapshot需要提前关闭虚拟机，教程未提及

### ISSUE THREAD

**Issue by lstfyt** [zstackorg/zstackorg.github.io#13]
Root volume 进行snapshot需要提前关闭虚拟机，教程未提及
![image](https://cloud.githubusercontent.com/assets/10667305/12680634/e0f982a0-c6e5-11e5-8d48-56b2451bb958.png)
注：英文版也未提及

**Comment by youyk** [comment]
it is because Ubuntu could support live snapshot. The live snapshot feature depends on Qemu capabilities in different OSes.
