### ISSUE TITLE
Manual Installation:zstack war包提示403 bug

### ISSUE THREAD

**Issue by yanhongchang** [zstackorg/zstackorg.github.io#2]
URL：http://zstack.org/installation/manual.html

2.6 2.6. Install ZStack WAR这步中 zstack 的下载地址应该是：
https://download.zstack.org/releases/0.6/war-0.6.2/zstack.war

![image](https://cloud.githubusercontent.com/assets/10663031/7679446/526b829c-fd8f-11e4-982c-2744ef4b3d0f.png)

**Comment by zxwing** [comment]
fixed in 500645d0b72ac962422ab3a32bc59c65c5accff0
