### ISSUE TITLE
Full-manual Install CentOS6.5/6.6./7  Ansible：

### ISSUE THREAD

**Issue by h5251032** [zstackorg/zstackorg.github.io#3]
http://zstack.org/installation/manual.html

![image](https://cloud.githubusercontent.com/assets/12522149/7718077/0ec136e0-fede-11e4-8a7b-beee6ec3a952.png)

**Comment by zxwing** [comment]
27a58774b03c58fb4a6aad1e9d2ca63c4c19ab32
